
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package simple;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LT = 10;
  public static final int ELSE = 19;
  public static final int SEMICOLON = 7;
  public static final int PLUS = 12;
  public static final int LEFT_BRACE = 4;
  public static final int LEFT_PAREN = 2;
  public static final int INT = 16;
  public static final int WHILE = 20;
  public static final int STAR = 14;
  public static final int SLASH = 15;
  public static final int IDENTIFIER = 26;
  public static final int RETURN = 21;
  public static final int TRUE = 22;
  public static final int IF = 18;
  public static final int GT = 11;
  public static final int BOOLEAN = 17;
  public static final int COMMA = 6;
  public static final int FUNC = 24;
  public static final int EOF = 0;
  public static final int INTEGER_LIT = 27;
  public static final int FALSE = 23;
  public static final int MINUS = 13;
  public static final int error = 1;
  public static final int ASSIGN = 8;
  public static final int EQ = 9;
  public static final int RIGHT_BRACE = 5;
  public static final int RIGHT_PAREN = 3;
  public static final int VAR = 25;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LEFT_PAREN",
  "RIGHT_PAREN",
  "LEFT_BRACE",
  "RIGHT_BRACE",
  "COMMA",
  "SEMICOLON",
  "ASSIGN",
  "EQ",
  "LT",
  "GT",
  "PLUS",
  "MINUS",
  "STAR",
  "SLASH",
  "INT",
  "BOOLEAN",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "TRUE",
  "FALSE",
  "FUNC",
  "VAR",
  "IDENTIFIER",
  "INTEGER_LIT"
  };
}

